# Generated by Django 5.0.6 on 2026-03-14 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_approval_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='approval_requested_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the user submitted their registration request.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who approved this registration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Staff-created and seeded users are auto-approved. Self-registered users start as False and cannot login until approved.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rejection_reason',
            field=models.CharField(blank=True, help_text='Optional reason shown to the user if their request is rejected.', max_length=500),
        ),
    ]
