"""
Merge migration — resolves the two conflicting 0003 leaf nodes:
  - 0003_alter_user_approval_requested_at_and_more  (auto-generated by makemigrations)
  - 0003_attachment_file_nullable                   (manually written)

Both are now parents of this merge so Django has a single leaf node.
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # The auto-generated one Django created on your machine
        ("core", "0003_alter_user_approval_requested_at_and_more"),
        # Our manually written one
        ("core", "0003_attachment_file_nullable"),
    ]

    operations = [
        # No operations needed — this is purely a merge node
    ]